### ISSUE TITLE
Cannot Find Consortia

### ISSUE THREAD

**Issue by tstxni97** [kaleido-io/kaleido-fabric-samples#5]
Assuming `API_KEY` is set correctly and running

```➜  node.js git:(master) ✗ node app.js
https://console.kaleido.io/api/v1/c
No business network found in the Kaleido account
```

However my consortia is not found even though I have two environments over there. 

![Screenshot from 2021-12-02 09-33-46](https://user-images.githubusercontent.com/2530093/144347101-7ecf5b10-3d06-4277-a57d-dc74a8785e72.png)

Maybe it's the region issue??

If I curl to create a new consortia, a new consortia is created. But this `ABC-DEV-QRM` is nowhere to be found.

**Comment by peterbroadhurst** [comment]
Hi @tstxni97 - yes, that does sound like you're using the 🇺🇸  API endpoint, to query for 🇦🇺  resources.
Details of finding the correct API are here: https://docs.kaleido.io/developers/automation/regions/

For an issue like this, the best thing is to raise it via the support center ❔  icon in the top-right of the console.
